inherit_gem:
  gitlab-styles:
    - rubocop-default.yml

inherit_from: .rubocop_todo.yml

AllCops:
  DisplayStyleGuide: false
  Exclude:
    - 'vendor/**/*'
    - 'ruby/vendor/**/*'
    - '_build/**/*'
