listen_addr = ":9999"
prometheus_listen_addr = ":9236"
bin_dir = "/app/_build/bin"

# # Git executable settings
[git]
bin_path = "/usr/local/bin/git"

[[storage]]
name = "default"
path = "/var/opt/gitlab/git-data"

# # You can optionally configure Gitaly to record histogram latencies on GRPC method calls
[prometheus]
grpc_latency_buckets = [0.001, 0.005, 0.025, 0.1, 0.5, 1.0, 10.0, 30.0, 60.0, 300.0, 1500.0]

[gitaly-ruby]
# The directory where gitaly-ruby is installed
dir = "/app/ruby"

[gitlab-shell]
# The directory where gitlab-shell is installed
dir = "/app/gitlab-shell"

[[concurrency]]
rpc = "/gitaly.RepositoryService/GarbageCollect"
max_per_repo = 1
