---
- name: Set run_name
  set_fact: "run_name=benchmark-{{ gitaly_revision }}-{{ lookup('pipe', 'date +%s') }}"

- name: Run benchmarks
  vars:
    output_dir: "/tmp/{{ run_name }}/{{ item.0.rpc }}/{{ item.1 }}"
  include_tasks: bench.yml
  loop: "{{ rpcs | product(repos) | list }}"

- name: Archive results
  archive:
    path:
    - "/tmp/{{ run_name }}"
    dest: "/tmp/{{ run_name }}.tar.gz"
    owner: git

- name: Fetch results
  fetch:
    src: "/tmp/{{ run_name }}.tar.gz"
    dest: "{{ playbook_dir }}/results/"
    flat: true
